# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-08 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20191108_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
